# Homework Set 4
# JuliaSet with numpy
# Done by Sidy Danioko


In [5]:
#!/usr/bin/env python
version = 0.2

# In here, let's define our class and its constructors
import math 

class JuliaSet:
    def __init__(self, c, m = 100):
        self.c = c
        self.m = m
        print " The complex part of the class is : ", self.c
        print  " The number of iteration is : ", self.m

                

In [7]:
JuliaSetObject = JuliaSet(1+1j,)

 The complex part of the class is :  (1+1j)
 The number of iteration is :  100


In [8]:
import math 

class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m
        print " The complex part of the class is : ", self.c
        print  " The number of iteration is : ", self.m
        print " The step size is : ", self._d

In [9]:
JuliaSetObject = JuliaSet(1+1j,)

 The complex part of the class is :  (1+1j)
 The number of iteration is :  100
 The step size is :  0.001


In [10]:
import math 

class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m
        print " The complex part of the class is : ", c
        print  " The number of iteration is : ", m
        

    def juliamap(self,z):
        return z**2 + self.c

In [11]:
juliaSetObject = JuliaSet(1+1j,)

 The complex part of the class is :  (1+1j)
 The number of iteration is :  100


In [12]:
import math 

class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m

    def juliamap(self,z):
        return z**2 + self.c
    
    def iterate(self,z):
        for counter in range(1,self.m+1): # Normally, this counter should start at zero. But, if we 
            # start zero, we will never know we went through the loop once
            z = self.juliamap(z)
            if math.sqrt(z.real**2 + z.imag**2) > 2 :
                return counter
        return 0
                

In [13]:
juliaSetObject = JuliaSet(10+10j)
juliaSetObject.iterate(1-1j)

1

In [16]:
import math 
import numpy as np
class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m
        self._complexplane = []
    def create_a_plane(self):
        self.limit = 2
        self.r = np.arange(-self.limit,self.limit,self._d)
        self._complexplane = self.r[:,np.newaxis] + self.r[np.newaxis,:]*1j # In here, we are creating two axis where each 
        # axis is from -2 to 2 subdisied equally with a step of 0.001
        



In [17]:
juliasetObject = JuliaSet(1+1j)
%timeit juliasetObject.create_a_plane()
juliasetObject._complexplane


10 loops, best of 3: 188 ms per loop


array([[-2.000-2.j   , -2.000-1.999j, -2.000-1.998j, ..., -2.000+1.997j,
        -2.000+1.998j, -2.000+1.999j],
       [-1.999-2.j   , -1.999-1.999j, -1.999-1.998j, ..., -1.999+1.997j,
        -1.999+1.998j, -1.999+1.999j],
       [-1.998-2.j   , -1.998-1.999j, -1.998-1.998j, ..., -1.998+1.997j,
        -1.998+1.998j, -1.998+1.999j],
       ..., 
       [ 1.997-2.j   ,  1.997-1.999j,  1.997-1.998j, ...,  1.997+1.997j,
         1.997+1.998j,  1.997+1.999j],
       [ 1.998-2.j   ,  1.998-1.999j,  1.998-1.998j, ...,  1.998+1.997j,
         1.998+1.998j,  1.998+1.999j],
       [ 1.999-2.j   ,  1.999-1.999j,  1.999-1.998j, ...,  1.999+1.997j,
         1.999+1.998j,  1.999+1.999j]])

In [ ]:
# As result by timing the _complexeplane in the first juliaset project, we that " 1 loops, best of 3: 7.99 s per loop ". 
# by using numpy, we can say the stratification of our complex plane was done in faster pace than that of using the list 

In [18]:
import math 
import numpy as np
class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m
        self._complexplane = []
    def create_a_plane(self):
        self.limit = 2
        self.r = np.arange(-self.limit,self.limit,self._d)
        self._complexplane = self.r[:,np.newaxis] + self.r[np.newaxis,:]*1j
        
        
    def juliamap(self,z):
        return z**2 + self.c
    
    def iterate(self,z):
        for counter in range(1,self.m+1):
            z = self.juliamap(z)
            if math.sqrt(z.real**2 + z.imag**2) > 2 :
                return counter
        return 0
    
    def set_spacing(self,d):
        self._d = d
        self.create_a_plane()
        return self._complexplane

In [20]:
juliasetObject = JuliaSet(1+1j)
juliasetObject.set_spacing(0.01)

array([[-2.00-2.j  , -2.00-1.99j, -2.00-1.98j, ..., -2.00+1.97j,
        -2.00+1.98j, -2.00+1.99j],
       [-1.99-2.j  , -1.99-1.99j, -1.99-1.98j, ..., -1.99+1.97j,
        -1.99+1.98j, -1.99+1.99j],
       [-1.98-2.j  , -1.98-1.99j, -1.98-1.98j, ..., -1.98+1.97j,
        -1.98+1.98j, -1.98+1.99j],
       ..., 
       [ 1.97-2.j  ,  1.97-1.99j,  1.97-1.98j, ...,  1.97+1.97j,
         1.97+1.98j,  1.97+1.99j],
       [ 1.98-2.j  ,  1.98-1.99j,  1.98-1.98j, ...,  1.98+1.97j,
         1.98+1.98j,  1.98+1.99j],
       [ 1.99-2.j  ,  1.99-1.99j,  1.99-1.98j, ...,  1.99+1.97j,
         1.99+1.98j,  1.99+1.99j]])

In [21]:
import math 
import numpy as np
class JuliaSet:
    def __init__(self, c, m = 100):
        self._d = 0.001
        self.c = c
        self.m = m
        self._complexplane = np.array([])
        self.set = np.array([])
    def create_a_plane(self):
        self.limit = 2
        self.r = np.arange(-self.limit,self.limit,self._d)
        self._complexplane = self.r[:,np.newaxis] + self.r[np.newaxis,:]*1j
        
        
    def juliamap(self,z):
        return z**2 + self.c
    
    def iterate(self,z):
        for counter in range(1,self.m+1):
            z = self.juliamap(z)
            if math.sqrt(z.real**2 + z.imag**2) > 2 :
                return counter
        return 0
    
    def set_spacing(self,d):
        self._d = d
        self.create_a_plane()
        return self._complexplane
    
    def generate(self):
        if not self._complexplane.size:
            self.create_a_plane()
            
        vfunc = np.vectorize(self.iterate)
        self.set = vfunc(self._complexplane)
        return self.set
        
        

In [22]:
juliasetObject = JuliaSet(1+ 1j)
juliasetObject.iterate(2-2j)
%timeit juliasetObject.generate()
juliasetObject.generate()

1 loops, best of 3: 44.2 s per loop


array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ..., 
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
# By running the generate function of the first julia set, we found as result that " 1 loops, best of 3: 57.3 s per loop ".
# By using numpy, we can see above that 1 loops, best of 3: 44.2 s per loop. One can then conclude that the use of numpy did 
# not drastically speed our generate function